spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/fanzone_notification
    username: fanzone
    password: fanzone
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8086
